export const INCREASE_COUNTER = 'INCREASE_COUNTER';
export const FETCH_DATA_BEGIN = 'FETCH_DATA_BEGIN';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const SET_DATA_BEGIN = 'SET_DATA_BEGIN';
export const SET_DATA_SUCCESS = 'SET_DATA_FAILURE_DATA_SUCCESS';
export const SET_DATA_FAILURE = 'SET_DATA_FAILURE';
