///////////// COUNT ACTION TYPES /////////////

export const FETCH_COUNT_BEGIN = 'FETCH_COUNT_BEGIN';
export const FETCH_COUNT_SUCCESS = 'FETCH_COUNT_SUCCESS';
export const FETCH_COUNT_FAILURE = 'FETCH_COUNT_FAILURE';

export const SET_COUNT_BEGIN = 'SET_COUNT_BEGIN';
export const SET_COUNT_SUCCESS = 'SET_COUNT_SUCCESS';
export const SET_COUNT_FAILURE = 'SET_COUNT_FAILURE';

///////////// GOALS ACTION TYPES /////////////

export const FETCH_GOALS_BEGIN = 'FETCH_GOALS_BEGIN';
export const FETCH_GOALS_SUCCESS = 'FETCH_GOALS_SUCCESS';
export const FETCH_GOALS_FAILURE = 'FETCH_GOALS_FAILURE';

export const SET_GOALS_BEGIN = 'SET_GOALS_BEGIN';
export const SET_GOALS_SUCCESS = 'SET_GOALS_SUCCESS';
export const SET_GOALS_FAILURE = 'SET_GOALS_FAILURE';

export const DELETE_GOAL_BEGIN = 'DELETE_GOAL_BEGIN';
export const DELETE_GOAL_SUCCESS = 'DELETE_GOAL_SUCCESS';
export const DELETE_GOAL_FAILURE = 'DELETE_GOAL_FAILURE';

///////////// POINTS GOAL TYPES /////////////

export const FETCH_POINTSGOAL_BEGIN = 'FETCH_POINTSGOAL_BEGIN';
export const FETCH_POINTSGOAL_SUCCESS = 'FETCH_POINTSGOAL_SUCCESS';
export const FETCH_POINTSGOAL_FAILURE = 'FETCH_POINTSGOAL_FAILURE';

export const SET_POINTSGOAL_BEGIN = 'SET_POINTSGOAL_BEGIN';
export const SET_POINTSGOAL_SUCCESS = 'SET_POINTSGOAL_SUCCESS';
export const SET_POINTSGOAL_FAILURE = 'SET_POINTSGOAL_FAILURE';
